version: '3.8'

services: 
    backend:
        container_name: test_serveur
       # image: node:lts
        build: ./
        command: npm start
        working_dir: /usr/src/backend
        environment:
            POSTGRES_USER: claver
            POSTGRES_PASSWORD: claver
            POSTGRES_DB: test-claver 
            POSTGRES_HOST: postgres
        ports:
            -  "3000:3000"
        links:
            - postgres
        volumes:
            - ./:/usr/src/backend

        # Postgres 
    postgres:       
        build: ./postgres
        environment:
            POSTGRES_USER: claver
            POSTGRES_PASSWORD: claver
            POSTGRES_DB: test-claver 
            POSTGRES_HOST: postgres
        ports: 
            - "5432:5432"
        
        
